CC=gcc
CFLAGS=-c -Wall -pthread
LDFLAGS=
SOURCES=procon0.c so0.c
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=procon0

all: $(SOURCES) $(EXECUTABLE)
	
$(EXECUTABLE): $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $< -o $@

clean:
	rm $(EXECUTABLES) *.*~
